[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_anchor_sveltekit_skeleton_starter = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://api.apr.dev"

[workspace]
types = "app/src/idl/"  # Will copy IDL to frontend app as TS (not JSON!)

[provider]
cluster = "http://localhost:8899" #"localnet" #"devnet"
wallet = "/Users/gaylonalfano/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
